markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 惊羽九天
host: /
desc: Discovers what the world hides

custom:
    category:
        default: 杂言碎语
        work:    作品发布
        tech:    伪技术贴
        clip:    网际偶得
    categories:
      - name:  default
        title: 杂言碎语

      - name:  work
        title: 作品发布

      - name:  tech
        title: 伪技术贴

      - name:  clip
        title: 网际偶得

meta:
    author:
        name: 惊羽九天
        email: mobius@toraleap.com
        disqus: toraleap                            # Disqus缩略标识
        gcse: 008584709401321574054:s8lt4ndvr2k     # Google自定义搜索标识ID
        github: toraleap                            # GitHub账号
        gravatar:                                   # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
